### ISSUE TITLE
Check task list component of govuk-frontend v5

### ISSUE THREAD

**Issue by sussexrick** [thepensionsregulator/govuk-frontend-aspnetcore-extensions#303]
As of govuk-frontend v5 task list is an official component. Our implementation is based on an earlier draft of that standard. govuk-frontend-aspnetcore v2.0.0, despite upgrading to govuk-frontend v5.1, does not yet include task list, so we still need to maintain our own code. However it should now align with the published standard.

- [x] Check that our HTML complies with GOV.UK design system examples
- [x] Check what CSS we can delete because it's now included in the core styles
- [x] Check before and after to make sure TPR task lists look the same

## Task list in TPR styles before changes
<img width="395" alt="Task list before changes" src="https://github.com/user-attachments/assets/05b2f20c-4e5c-459a-955f-f309e4c488ce">
